general.import = ["~/.config/alacritty/theme-active.generated.toml"]

[env]
TERM = "xterm-256color"

#===============================================================================
# Window
#===============================================================================
[window]
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "Both"

  [window.padding]
  x = 5
  y = 5

#===============================================================================
# Font
#===============================================================================
[font]
size = 14

  [font.normal]
  family = "Menlo"
  style = "Regular"

  [font.offset]
  x = 0
  y = 0

#===============================================================================
# Cursor
#===============================================================================
[cursor]
blink_interval = 500
blink_timeout = 0

  [cursor.style]
  shape = "Block"
  blinking = "Always"
