# Clipboard synchronization
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'xsel -i -b' \; display-message "copied to system clipboard"
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'xsel -i -b' \; display-message "copied to system clipboard"

# --- Linux 专用配置 ---
# 保持深色背景
set-option -g status-bg "colour238"
set-option -g status-fg "colour250"

# 状态栏左侧
set-option -g status-left "#[fg=colour255,bg=colour238]#{?client_prefix,#[reverse],} Session: #S #[default]"

# 状态栏右侧：直接传入 Linux 喜欢的深色模式颜色
set-option -g status-right "#[fg=colour250,bg=colour238] #(~/.config/tmux/bin/cpu_load.sh '121' '220' '197') #[default]"
