# Clipboard synchronization for vi copy mode
set-option -s set-clipboard on
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy" \; display-message "copied to system clipboard"
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy" \; display-message "copied to system clipboard"
