# Clipboard synchronization for vi copy mode
set-option -s set-clipboard on
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy" \; display-message "copied to system clipboard"
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy" \; display-message "copied to system clipboard"


# Enable pane scrollbars in modal mode (modal, on, off)
set -g pane-scrollbars off

# Set scrollbar position: left or right
set -g pane-scrollbars-position right

# Set pane scrollbars style
set-option -g pane-scrollbars-style "fg=#708284"