# Clipboard synchronization for vi copy mode
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy" \; display-message "copied to system clipboard"
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy" \; display-message "copied to system clipboard"

# Watch macOS appearance changes and refresh tmux theme
run-shell -b ~/.config/tmux/scripts/theme_watch.sh

if-shell "defaults read -g AppleInterfaceStyle 2>/dev/null | grep -q Dark" {
    # --- 深色模式 (Dark) ---
    set-option -g status-bg "colour238"
    set-option -g status-fg "colour250"

    # 颜色参数：正常:76(绿), 警告:142(黄), 高压:160(红)
    set-option -g status-right "#[fg=colour250,bg=colour238] #(~/.config/tmux/scripts/cpu_load.sh '76' '142' '160') #[default]"
    set-option -g status-left "#[fg=colour255,bg=colour238]#{?client_prefix,#[reverse],} Session: #S #[default]"
} {
    # --- 浅色模式 (Light) ---
    set-option -g status-bg "colour255"
    set-option -g status-fg "colour239"

    # 颜色参数：正常:34(深绿), 警告:100(黄褐), 高压:124(深红)
    set-option -g status-right "#[fg=colour239,bg=colour255] #(~/.config/tmux/scripts/cpu_load.sh '34' '100' '124') #[default]"
    set-option -g status-left "#[fg=colour239,bg=colour255]#{?client_prefix,#[reverse],} Session: #S #[default]"
}
