# Interval for updating the status line
set-option -g status-interval 5

# Specify the maximum length of status-left
set-option -g status-left-length 40

# Specify the maximum length of status-right
set-option -g status-right-length 60

# Solarized Dark defaults
set-option -g status-bg "#073642"
set-option -g status-fg "#839496"
set-option -g status-left "#[fg=#eee8d5,bg=#073642]#{?client_prefix,#[reverse],} Session: #S #[default]"
set-option -g status-right "#[fg=#839496,bg=#073642] #(~/.config/tmux/bin/cpu_load.sh '#859900' '#b58900' '#dc322f') #[default]"
set-window-option -g window-status-format "#[fg=#93a1a1,bg=#073642] #I: #W #[default]"
set-window-option -g window-status-current-format "#[fg=#fdf6e3,bg=#268bd2,bold] #I: #W #[default]"
