# Interval for updating the status line
set-option -g status-interval 1
set-option -g @cpu_load ""
run-shell -b 'TMUX_CPU_LOAD_INTERVAL=1 ~/.config/tmux/bin/cpu-load-daemon.sh "#738a05" "#a57706" "#d11c24"'

# Specify the maximum length of status-left
set-option -g status-left-length 40

# Specify the maximum length of status-right
set-option -g status-right-length 60

# Solarized Dark - Patched
set-option -g status-bg "#002831"
set-option -g status-fg "#708284"
set-option -g pane-border-style "fg=#475b62"
set-option -g pane-active-border-style "fg=#2176c7"
set-option -g status-left "#[fg=#708284,bg=#002831]#{?client_prefix,#[reverse],} Session: #S #[default]"
set-option -g status-right "#[fg=#708284,bg=#002831] #{@cpu_load} #[default]"
set-window-option -g window-status-format "#[fg=#708284,bg=#002831] #I: #W #[default]"
set-window-option -g window-status-current-format "#[fg=#002831,bg=#2176c7,bold] #I: #W #[default]"
