# Interval for updating the status line
set-option -g status-interval 1
set-option -g @cpu_load ""
run-shell -b 'TMUX_CPU_LOAD_INTERVAL=1 ~/.config/tmux/bin/cpu-load-daemon.sh "#98971a" "#d79921" "#cc241d"'

# Specify the maximum length of status-left
set-option -g status-left-length 40

# Specify the maximum length of status-right
set-option -g status-right-length 60

# Gruvbox Dark Hard
# https://github.com/morhetz/gruvbox
set-option -g status-bg "#282828"
set-option -g status-fg "#ebdbb2"
set-option -g message-bg "#504945"
set-option -g message-fg "#ebdbb2"
set-option -g message-command-bg "#504945"
set-option -g message-command-fg "#ebdbb2"
set-option -g mode-bg "#458588"
set-option -g mode-fg "#ebdbb2"
set-option -g pane-border-style "fg=#504945"
set-option -g pane-active-border-style "fg=#458588"

set-option -g status-left "#[fg=#ebdbb2,bg=#282828]#{?client_prefix,#[reverse],} ^ #[default]"
set-option -g status-right "#[fg=#ebdbb2,bg=#282828] #{@cpu_load} #[default]"

set-window-option -g window-status-format "#[fg=#ebdbb2,bg=#282828] #I #[default]"
set-window-option -g window-status-current-format "#[fg=#282828,bg=#458588,bold] #I #[default]"

set-window-option -g window-status-activity-style "fg=#cc241d"
set-window-option -g window-status-bell-style "fg=#cc241d,bg=#282828 blink"