# Interval for updating the status line
set-option -g status-interval 5

# Specify the maximum length of status-left
set-option -g status-left-length 40

# Specify the maximum length of status-right
set-option -g status-right-length 60

# Selenized Dark defaults
set-option -g status-bg "#184956"
set-option -g status-fg "#adbcbc"
set-option -g pane-border-style "fg=#72898f"
set-option -g pane-active-border-style "fg=#4695f7"
set-option -g status-left "#[fg=#cad8d9,bg=#184956]#{?client_prefix,#[reverse],} Session: #S #[default]"
set-option -g status-right "#[fg=#adbcbc,bg=#184956] #(~/.config/tmux/bin/cpu_load.sh '#75b938' '#dbb32d' '#fa5750') #[default]"
set-window-option -g window-status-format "#[fg=#cad8d9,bg=#184956] #I: #W #[default]"
set-window-option -g window-status-current-format "#[fg=#103c48,bg=#4695f7,bold] #I: #W #[default]"
