# Interval and lengths are defined in statusline-dark.conf.

# Solarized Light overrides
set-option -g status-bg "#eee8d5"
set-option -g status-fg "#586e75"
set-option -g pane-border-style "fg=#93a1a1"
set-option -g pane-active-border-style "fg=#268bd2"
set-option -g status-left "#[fg=#586e75,bg=#eee8d5]#{?client_prefix,#[reverse],} Session: #S #[default]"
set-option -g status-right "#[fg=#586e75,bg=#eee8d5] #(~/.config/tmux/bin/cpu_load.sh '#859900' '#b58900' '#dc322f') #[default]"
set-window-option -g window-status-format "#[fg=#657b83,bg=#eee8d5] #I: #W #[default]"
set-window-option -g window-status-current-format "#[fg=#fdf6e3,bg=#268bd2,bold] #I: #W #[default]"
