# Interval for updating the status line
set-option -g status-interval 5

# Specify the status line style
set-option -g status-style "fg=colour255,bg=colour238"

# Specify the maximum length of status-left
set-option -g status-left-length 40

# Specify the format of status-left
set-option -g status-left "#[fg=colour255,bg=colour238]#{?client_prefix,#[reverse],} Session: #S #[default]"

# Specify the maximum length of status-right
set-option -g status-right-length 60

# Specify the format of window-status
set-window-option -g window-status-format " #I: #W "

# Specify the format of the window-status of the current window
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour63,bold] #I: #W #[default]"
