# General

# Enable mouse operation
set-option -g mouse on

# Clipboard synchronization via OSC 52, including nested tmux
set-option -s set-clipboard on

# Set history limit
set-option -g history-limit 100000

# Set base index
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on

# Import configurations

# Import bindings
source-file ~/.config/tmux/conf/bindings.conf

# Import terminal
source-file ~/.config/tmux/conf/terminal.conf

# Import statusline
source-file ~/.config/tmux/conf/statusline.conf

