#! /bin/sh

pgrep -x panel > /dev/null || panel &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width        3
bspc config window_gap          5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config automatic_scheme alternate

bspc rule -a Emacs state=tiled
bspc rule -a Google Chrome desktop='^2'
