#===============================================================================
# window
#===============================================================================
window:
  # 窗口的外边框
  #
  # 可以为如下的值:
  #     - full: 边框和标题栏
  #     - none: 边框和标题栏都没有
  #
  # macos 可以独占的配置:
  #     - transparent: 标题栏，透明背景和标题栏按钮
  #     - buttonless: 标题栏，透明背景，但没有标题栏按钮
  decorations: buttonless

  # 窗口内边距（配置变更需要重启生效）
  #
  # 调整窗口的内边距（单位为像素）。此填充由DPI缩放，并且始终在相对的两边添加指定的值。
  # 注解：内边距是窗口边框相对于终端显示内容的空白部分，可以参考 CSS
  padding:
    x: 8
    y: 8
  # 在终端内容周围平均分配额外的 padding
  # dynamic_padding: false
  # 窗口标题
  # title: Alacritty
  # 是否允许终端的应用更改窗口标题
  # dynamic_title: true
# 背景透明度
# background_opacity: 0.99

#===============================================================================
# font
#===============================================================================
font:
  # 常规字体
  normal:
    family: MesloLGM Nerd Font
    # 字体风格
    style: Regular

  # 粗体
  bold:
    family: Menlo
    style: Bold

  # 斜体
  italic:
    family: Menlo
    style: Italic

  # 斜粗体
  bold_italic:
     family: Menlo
     style: Bold Italic

  # 字体大小
  size: 14

  # 每个字符的间的字间距。"offset.y" 可以控制行距，"offset.x" 可以改变字符间距。
  offset:
    x: 0
    y: 0
  # 细线字体渲染（仅适用于macOS）
  # retina 可以设置为 true，非 retina 屏幕建议设置为 false
  use_thin_strokes: true
# If `true`, bold text is drawn using the bright color variants.
# draw_bold_text_with_bright_colors: true

#===============================================================================
# key_bindings
# 解决 中文输入法 退格问题 https://github.com/alacritty/alacritty/issues/1606
# 解决 Ctrl-Space 失效问题
# @see https://github.com/alacritty/alacritty/issues/1652
# 解决 Emacs 键位 失效问题
# @see https://github.com/alacritty/alacritty/issues/93#issuecomment-334790547
# 禁用方向键
#===============================================================================
key_bindings:
  - { key: Back, action: ReceiveChar }
  - { key: Space, mods: Control, chars: "\0" }
  - { key: F, mods: Alt, chars: "\ef" }
  - { key: B, mods: Alt, chars: "\eb" }
  - { key: D, mods: Alt, chars: "\ed" }

  - { key: Up, chars: "" }
  - { key: Down, chars: "" }
  - { key: Left, chars: "" }
  - { key: Right, chars: "" }

