config-version = 2
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'accordion'
default-root-container-orientation = 'horizontal'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

persistent-workspaces = ["1", "2", "3", "4", "5"]

[key-mapping]
    preset = 'qwerty'

[mode.main.binding]
    alt-enter = '''exec-and-forget open -a Kitty'''
    alt-backtick = '''exec-and-forget kitten quick-access-terminal'''
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'

    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    f = ['layout floating tiling', 'mode main']

[workspace-to-monitor-force-assignment]
    "1" = 1

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['move-node-to-workspace 5']
