# Prefix
set-option -g prefix C-\\
unbind C-b
bind C-\\ send-prefix

# Vi copy mode
set-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel \; display-message "copied"
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel \; display-message "copied"

# Configuration
bind r source-file ~/.config/tmux/tmux.conf \; display-message "reloaded"

# Sessions
bind C-c new-session

# Pane splitting
bind - split-window -v -c "#{pane_current_path}"
bind = split-window -h -c "#{pane_current_path}"

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Windows
bind -r tab select-window -t +1
bind e set-window-option synchronize-panes \; display-message "synchronize-panes #{?synchronize-panes,on,off}"
