# Interval for updating the status line
set-option -g status-interval 5

# Specify the maximum length of status-left
set-option -g status-left-length 40

# Specify the maximum length of status-right
set-option -g status-right-length 60

# Gruvbox Dark
set-option -g status-bg "#3c3836"
set-option -g status-fg "#ebdbb2"
set-option -g pane-border-style "fg=#3c3836"
set-option -g pane-active-border-style "fg=#665c54"

set-option -g status-left "#[fg=#fbf1c7,bg=#{?pane_synchronized,#cc241d,#3c3836}]#{?client_prefix,#[reverse],}#{?window_zoomed_flag, z, ^} #[default]"
set-option -g status-right '#[fg=#ebdbb2,bg=#3c3836] #(~/.config/tmux/bin/cpu-load.sh "#b8bb26" "#fabd2f" "#fb4934") #[default]'

set-window-option -g window-status-format "#[fg=#ebdbb2,bg=#3c3836] #I #[default]"
set-window-option -g window-status-current-format "#[fg=#fbf1c7,bg=#665c54,bold] #I #[default]"

set-window-option -g window-status-activity-style "fg=#b8bb26"
set-window-option -g monitor-bell off
set-option -g bell-action none
