# General

# Change the prefix key
set-option -g prefix C-\\
unbind C-b
bind C-\\ send-prefix

# vim keybinding
set-option -g mode-keys vi

# Enable mouse operation
set-option -g mouse on

# Focus on terminal events
set-option -g focus-events on

# Reduce keystroke delay
set-option -sg escape-time 10

# Reload configuration
bind r source-file ~/.config/tmux/tmux.conf \; display 'tmux.conf sourced'

# Use 256 color terminal
set-option -g default-terminal "screen-256color"

# 24 bit color support
set-option -ga terminal-features ",screen-256color:RGB,xterm-256color:RGB,screen-256color:clipboard"

# Navigation

# Create session
bind C-c new-session

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Status Line
source-file ~/.config/tmux/conf/statusline.conf

# Import
if-shell '[ "$(uname -s)" = "Darwin" ]' {
  source-file ~/.config/tmux/conf/macos.conf
}

if-shell '[ "$(uname -s)" = "Linux" ]' {
  source-file ~/.config/tmux/conf/linux.conf
}
